---
title: "第一章 时间序列分析简介"
author: "Jin's students"
date: "2019-11-23"
output:
  bookdown::html_document2:
    number_sections: true
    seq_numbering: true
    fig_caption: true
    highlight: haddock
    theme: null
    md_extensions: +east_asian_line_breaks
    keep_md: true
    toc: true
    pandoc_args: ["--filter", "pandoc-crossref", "-M", "eqnPrefix="]
  bookdown::word_document2:
    fig_caption: true
    reference_docx: ./style/word-styles-02.docx
    md_extensions: +east_asian_line_breaks
    pandoc_args: ["--filter", "pandoc-crossref"]
  bookdown::pdf_document2:
    keep_tex: yes
    toc: false
    latex_engine: xelatex
    md_extensions: +east_asian_line_breaks
    pandoc_args: ["--listing", "--filter", "pandoc-crossref"]
css: ./style/markdown.css
autoEqnLabels: true
eqnPrefixTemplate: ($$i$$)
linkReferences: true
bibliography: Bibfile.bib
csl: ./style/chinese-gb7714-2005-numeric.csl
link-citations: true
---
# 教材介绍
1. 教材：《应用时间序列 in R》，王燕编著，中国人民大学出版社。
2. 应用软件：R
3. 练习数据库：Time Series Data Library[下载网址](http://datamarket.com/data/list/?q=provider:tsdl)

# 时间序列的定义
1. 随机序列：按时间顺序排列的一组随机变量。
2. 观察值序列：随机序列的n个有序观察值，称之为序列长度为n的观察值序列。
3. 随机序列和观察值序列的关系:

  （1）观察值序列是随机序列的一个实现。
  
  （2）研究的目的一致，都是揭示随机时间序列的性质。
  
  （3）实现的手段一致，都是通过分析观察值序列的性质，由观察值序列的性质来推断随机序列的性质。


# 时间序列分析方法简介
## 描述性时序分析
1. 定义：通过直观的数据比较或绘图观测，寻找序列中蕴含的发展规律。
2. 特点：操作简单、直观有效，是进行统计时序分析的第一步。
3. 局限性：它只能展示非常明显的规律性。而对于金融、保险等社会科学研究领域，随机变量的发展通常会呈现出非常强的随机性，想通过对序列简单的观察和描述，总结出随机变量发展变化的规律，并准确预测出它们将来的走势通常是非常困难的。 

## 统计时序分析
1. 定义：利用数理统计学的基本原理，分析序列值内在的相关关系 。
2. 在统计时序分析方法中，分为频域分析方法和时域分析方法两大类。

### 频域分析方法
1. 原理：假设任何一种无趋势的时间序列都可以分解成若干不同频率的周期波动。
2. 特点：是一种非常有用的动态数据分析方法，但是由于分析方法复杂，结果抽象，有一定的使用局限性。

### 时域分析方法
1. 原理：事件的发展通常都具有一定的惯性，这种惯性用统计的语言来描述就是序列值之间存在着一定的相关关系，这种相关关系通常具有某种统计规律。
2. 目的：寻找出序列值之间相关关系的统计规律，并拟合出适当的数学模型来描述这种规律，进而利用这个拟合模型预测序列未来的走势。
3. 特点：理论基础扎实，操作步骤规范，分析结果易于解释，是时间序列分析的主流方法。
4. 步骤：

  （1）考察观察值序列的特征
  
  （2）根据序列特征选择适当的拟合模型
  
  （3）根据序列的观察数据确定模型的口径
  
  （4）检验模型，优化模型
  
  （5）利用拟合好的模型来推断序列其它的统计性质或预测序列将来的发展\
5. 发展过程：启蒙阶段——基础阶段——发展阶段
  
---




