---
title: "第二章&ensp;时间序列的预处理"
author: "Jin's students"
date: "2019-11-23"
output:
  bookdown::html_document2:
    number_sections: true
    seq_numbering: true
    fig_caption: true
    highlight: haddock
    theme: null
    md_extensions: +east_asian_line_breaks
    keep_md: true
    toc: true
    pandoc_args: ["--filter", "pandoc-crossref", "-M", "eqnPrefix="]
  bookdown::word_document2:
    fig_caption: true
    reference_docx: ./style/word-styles-02.docx
    md_extensions: +east_asian_line_breaks
    pandoc_args: ["--filter", "pandoc-crossref"]
  bookdown::pdf_document2:
    keep_tex: yes
    toc: false
    latex_engine: xelatex
    md_extensions: +east_asian_line_breaks
    pandoc_args: ["--listing", "--filter", "pandoc-crossref"]
css: ./style/markdown.css
autoEqnLabels: true
eqnPrefixTemplate: ($$i$$)
linkReferences: true
bibliography: Bibfile.bib
csl: ./style/chinese-gb7714-2005-numeric.csl
link-citations: true
---
# 时间序列预处理含义
对于一组观察值序列，首先要对它的**平稳性**和**纯随机性**进行检验，这两个重要的检验称为序列的预处理。根据检验的结果将序列分为不同的类型，进而对不同类型的序列采取不同的分析方法。

# 平稳性检验
## 概率分布特征统计量
1. 概率分布

  任取正整数m，任取$t_{1}, t_{2}, \cdots, t_{m} \in T$，则m维随机向量$\left(X_{t_{1}}, X_{t_{2}}, \cdots,\right.\left.X_{t_{m}}\right)^{\prime}$的联合概率分布记为$\ {F_{{t_1},{t_2}, \cdots ,{t_m}}}({x_1},{x_2}, \cdots ,{x_m}) {\kern 1pt} {\kern 1pt} {\kern 1pt} {\kern 1pt} {\kern 1pt} {\kern 1pt} {\kern 1pt}$,由这些有限维分布函数构成的全体
    $$\{ {F_{{t_1},{t_2}, \cdots ,{t_m}}}({x_1},{x_2}, \cdots ,{x_m})\} {\kern 1pt} {\kern 1pt} {\kern 1pt} {\kern 1pt} {\kern 1pt} {\kern 1pt} {\kern 1pt} ,\forall m \in (1,2, \cdots ,m),\forall {t_1},{t_2}, \cdots ,{t_m} \in T$$
    就称为序列$\left\{X_{t}\right\}$的概率分布族。

2. 特征统计量

  时间序列的低阶矩，如均值、方差、自协方差和自相关系数，都被称为特征统计量。通过分析这些特征统计量，推出随机序列的性质。
  
2.1 均值:反映时间序列每时每刻的平均水平
$${\mu _t} = E{X_t} = \int_{ - \infty }^\infty  {xd{F_t}(x)} $$

2.2 方差：描述时间序列值围绕其均值做随机波动时平均的波动程度
  $$D{X_t} = E{({X_t} - {\mu _t})^2} = {\int_{ - \infty }^\infty  {(x - {\mu _t})} ^2}d{F_t}(x)$$

2.3 自协方差函数
$$\gamma (t,s) = E({X_t} - {\mu _t})({X_s} - {\mu _s})$$

2.4 自相关系数（简记为ACF）
$$\rho (t,s) = \frac{{\gamma (t,s)}}{{\sqrt {D{X_t} \cdot D{X_s}} }}$$
自协方差函数和自相关系数度量的是同一事件在两个不同时期之间的相关程度，形象的讲就是度量自己过去的行为对自己现在的影响。

## 平稳时间序列的定义
### 严平稳定义
严平稳：序列所有的统计性质都不会随着时间的推移而发生变化,我们知道随机变量族的统计性质完全由他们的联合概率分布族决定的，所以，设$\left\{X_{t}\right\}$为一时间序列，对任意正整数m，任取$t_{1}, t_{2}, \cdots, t_{m} \in T$，对于任意正整数$\tau$,有
$$F_{t_{1}, t_{2} \cdots t_{m}}\left(x_{1}, x_{2}, \cdots, x_{m}\right)=F_{t_{1+r}} \cdot t_{2+r_{r} \cdots t_{m+r}}\left(x_{1}, x_{2}, \cdots, x_{m}\right)$$
则称时间序列$\left\{X_{t}\right\}$为严平稳时间序列。

### 宽平稳定义
  宽平稳（也称弱平稳或二阶平稳）是使用序列的特征统计量来定义的一种平稳性。它认为序列的统计性质主要由它的低阶矩决定，所以只要保证序列低阶矩平稳（二阶），就能保证序列的主要性质近似稳定。
  
  如果$\left\{X_{t}\right\}$满足三个条件：
  
  （1）$EX_t^2 < \infty ,\forall t \in T$
  
  （2）$E{X_t} = \mu ,\forall t \in T$，且$\mu$为常数
  
  （3）$\gamma (t,s) = \gamma (k,k + s - t),\forall t,s,k且k + s - t \in T$
  
则称$\left\{X_{t}\right\}$为宽平稳时间序列。

### 宽平稳和严平稳的关系
严格来讲，宽平稳推不出严平稳，只有当序列服从多元正态分布时，二阶平稳可以推出严平稳，换言之，宽平稳正态事件序列一定是严平稳时间序列。对于非正态过程，就没有这个性质。严平稳也推不出宽平稳，只有存在二阶矩的严平稳序列才能保证一定是宽平稳序列。比如柯西分布的严平稳序列就不是宽平稳序列。

实际应用中，平稳随机序列指宽平稳随机序列，若序列不满足平稳条件，则成为非平稳序列。

## 平稳时间序列的统计性质
1. 均值为常数
2. 自协方差函数和自相关函数只依赖于时间的平移长度而与时间的起止点无关
$$\gamma(t, s)=\gamma(k, k+s-t), \forall t, s, k \in T$$
2.1 延迟k自协方差函数 
\[\gamma (k) = \gamma (t,t + k),\forall k\]
2.2 延迟k自相关系数
\[{\rho _k} = \frac{{\gamma (k)}}{{\gamma (0)}}\]
和相关系数一样，自相关系数具有如下四个性质：

（1）规范性
\[{\rho _0} = 1，\left| {{\rho _k}} \right| \le 1{\kern 1pt} ,\forall k\]

（2）对称性
\[{\rho _k} = {\rho _{ - k}}\]

（3）非负定性
\[\begin{array}{l}
{\Gamma _m为非负定阵，}{\kern 1pt} {\kern 1pt} \forall正整数 m{\kern 1pt} {\kern 1pt} {\kern 1pt} {\kern 1pt} {\kern 1pt} {\kern 1pt} \\
{\Gamma _m} = \left( {\begin{array}{*{20}{c}}
{{\rho _0}}&{{\rho _1}}& \cdots &{{\rho _{m - 1}}}\\
{{\rho _1}}&{{\rho _0}}& \cdots &{{\rho _{m - 2}}}\\
 \vdots & \vdots & \cdots & \vdots \\
{{\rho _{m - 1}}}&{{\rho _{m - 2}}}& \cdots &{{\rho _0}}
\end{array}} \right)
\end{array}\]

（4）非唯一性

一个平稳时间序列一定唯一决定了它的自相关函数，但一个自相关函数未必唯一对应着一个平稳时间序列。

## 平稳时间序列的意义
* 在平稳序列场合，序列的均值等于常数，这意味着原本含有可列多个随机变量的均值序列变成了只含有一个变量的常数序列
$$\{ {\mu _t},t \in T\}  {\kern 1pt}  \Rightarrow {\kern 1pt}  \{ \mu ,t \in T\}$$
* 原本每个随机变量的均值（方差，自相关系数）只能依靠唯一的一个样本观察值去估计，现在由于平稳性，每一个统计量都将拥有大量的样本观察值。
$$\hat \mu  = {x_t}\Rightarrow \hat \mu =\bar{x}= \frac{\sum_{i = 1}^{n}x_i}{n}$$
基于全体样本观察值计算出延迟k自协方差函数的估计值 
$$\widehat{\gamma}(k)=\frac{\sum_{t=1}^{n-k}\left(x_{t}-\bar{x}\right)\left(x_{t+k}-\bar{x}\right)}{n-k}, \quad \forall 0<k<n$$
进一步推导出总体方差的估计值、延迟k自相关系数的估计值 
$$\widehat{\gamma}(0)=\frac{\sum_{t=1}^{n}\left(x_{t}-\bar{x}\right)^{2}}{n-1}$$
\[{\hat \rho _k} = \frac{{\hat \gamma (k)}}{{\hat \gamma (0)}}\forall {\rm{0 < k < n}}\]
当延迟阶数k远远小于样本容量n时
$$\widehat{\rho}_{k} \approx \frac{\sum_{t=1}^{n-k}\left(x_{t}-\bar{x}\right)\left(x_{t+k}-\bar{x}\right)}{\sum_{t=1}^{n}\left(x_{t}-\bar{x}\right)^{2}}, \quad \forall 0<k<n$$
综合以上分析，平稳时间序列极大地减少了随机变量的个数，并增加了待估变量的样本容量。极大地简化了时序分析的难度，同时也提高了对特征统计量的估计精度

## 平稳性的检验
对于序列的平稳性有两种检验方法，一种是根据时序图和自相关图显示的特征做出判断的图检验法；一种是构造检验统计量进行假设检验的方法。本章将主要介绍平稳性的图检验方法。

### 时序图检验
根据平稳时间序列均值、方差为常数的性质，平稳序列的时序图应该显示出该序列始终在一个常数值附近随机波动，而且波动的范围有界、无明显趋势及周期特征

### 自相关图检验
自相关图是一个平面二维坐标悬垂线图，横坐标表示延迟时期数，另一个坐标表示自相关系数，悬垂线表示自相关系数的大小。平稳序列通常具有短期相关性。该性质用自相关系数来描述就是随着延迟期数的增加，平稳序列的自相关系数会很快地衰减向零，反之，非平稳序列的自相关系数衰减向零的速度通常比较慢，利用这一特性，我们可以利用自相关图进行平稳性判断。

# 纯随机性检验
## 纯随机序列的定义
如果时间序列$\left\{X_{t}\right\}$满足如下性质：
\[\begin{array}{l}
(1)E{X_t} = \mu {\kern 1pt} {\kern 1pt} {\kern 1pt} {\kern 1pt} ,{\kern 1pt} {\kern 1pt} {\kern 1pt} {\kern 1pt} \forall t \in T\\
(2)\gamma (t,s) = \left\{ {\begin{array}{*{20}{c}}
{{\sigma ^2},t = s}\\
{0,t \ne s}
\end{array}} \right.{\kern 1pt}\forall t,s \in T
\end{array}\]
称序列$\left\{X_{t}\right\}$为纯随机序列（常数均值，同方差，无序列自相关），也称白噪声序列，简记为$WN(\mu,\sigma ^2)$。白噪声序列一定是平稳序列，而且是最简单的平稳序列。

## 纯随机序列的性质
1. 纯随机性：各序列值之间没有任何相关关系，即为 “没有记忆”的序列。 \[\gamma (k) = 0，\forall k \ne 0\]
纯随机性也是我们判断相关信息是否提取充分的一个判别标准。一旦观察值序列中蕴含的相关信息被我们充分提取出来了，那么剩下的残差序列就应该呈现出纯随机的性质了。
2. 方差齐性：根据马尔可夫定理，只有拟合模型残差的方差齐性假定成立时，用最小二乘法得到的未知参数估计值才是准确的、有效的
\[D{X_t} = \gamma (0) = {\sigma ^2}\]

## 纯随机性检验
### 检验原理
如果一个时间序列是纯随机的，得到一个观察期数为  的观察序列，那么该序列的延迟非零期的样本自相关系数将近似服从均值为零，方差为序列观察期数倒数的正态分布
$${\hat\rho _k} \dot\sim N(0,\frac{1}{n}),\forall k \ne 0$$

### 假设条件
原假设：延迟期数小于或等于m期的序列值之间相互独立
\[{H_0}:{\rho _1} = {\rho _2} =  \cdots  = {\rho _m} = 0,\forall m \ge 1\]

备择假设：延迟期数小于或等于m期的序列值之间有相关性 
\[{H_1}:至少存在某个{\rho _k} \ne 0,\forall m \ge 1，k \le m\]

### 检验统计量
1. Q统计量（大样本）,又称$Q_{BP}$统计量
\[Q = n\sum\limits_{k = 1}^m {\hat \rho _k^2}  \sim {\chi ^2}(m)\]
其中n为序列观测期数，m为指定延迟期数。
2. LB统计量（小样本）,又称$Q_{LB}$统计量
\[LB = n(n + 2)\sum\limits_{k = 1}^m {(\frac{{\hat \rho _k^2}}{{n - k}})} \sim {\chi ^2}(m)\]
其中n为序列观测期数，m为指定延迟期数。

### 判别原则
1. 拒绝原假设：当检验统计量大于$\chi _{1 - \alpha }^2(m)$分位点，或该统计量的P值小于$\alpha$时，则可以以 $1-\alpha$  的置信水平拒绝原假设，认为该序列为非白噪声序列。
2. 接受原假设：当检验统计量小于$\chi _{1 - \alpha }^2(m)$分位点，或该统计量的P值大于$\alpha$时，则认为在 $1-\alpha$  的置信水平无法拒绝原假设，即不能显著拒绝序列为纯随机序列的假定 。

### R中Box.test函数
R语言中使用Box.test函数进行纯随机性检验（白噪声检验）。
```
Box.test(x,type=,lag=)
-x:时间序列名
-type:检验统计量的类型
type='Box-Pierce',Q统计量，默认
type='Ljung-Box',LB统计量
-lag:延迟阶数，lag=n表示输出滞后n阶的白噪声检验统计量，默认滞后1阶。
```
# R程序实现
```{r}
#实验一
rm(list = ls())
setwd('D:/时间序列分析/习题数据、案例数据、R代码/')
dat1 <- read.csv("data/file1.csv",header = T)
#变量yield的时间序列图
plot(dat1$yield~dat1$Year,xlab='Year',ylab = 'yield',type='o',col='blue')
#样本自相关系数
Acf <- function(x,k){
  n=length(x)
  fenzi=0
  xba <- mean(x)
  fenmu <- (n-1)*var(x)
  for (i in 1:(n-k)) {
    s <- (x[i]-xba)*(x[i+k]-xba)
    fenzi <- fenzi+s
  }
  Corr <- fenzi/fenmu
  return(Corr)
}
for (i in 1:24) print(Acf(dat1$yield,i))#输出样本自相关系数
corr <- acf(dat1$yield,lag.max = 24)
corr$acf#检验和上面函数结果一致
#自相关图显示该序列的自相关系数一直比较小，始终控制在2倍标准差范围内，可以认为该序列、
#自始至终都在零轴附近随机波动，不存在趋势和周期性，可以认为该序列是平稳的。

#实验二
Index <- read.csv('data/file2.csv',header = T)
plot(Index$index~Index$Year,type='o',lwd=2,col="blue",main="Index时序图")#画出时间序列图
#绘制样本自相关图，计算样本自相关系数
for (i in 1:24) {
  print(Acf(Index$index,i))
}
corr2 <- acf(Index$index,lag.max = 24)
corr2
#时序图有明显的递增趋势，样本自相关系数始终在2倍标准差范围内，该序列是非平稳时间序列

#判断时间序列的纯随机性
#构造检验统计量——Q统计量（n=19，样本容量小）
n=19#序列观测期数
m=6#延迟期数
Q=n*sum((corr2$acf^2)[1:m])
p=1-pchisq(Q,m,ncp=0,lower.tail = T,log.p = F)
p
Box.test(Index$index,lag = 6,type = "Box-Pierce")
#P值为1.110223e-16，在显著性水平为0.05下，拒绝原假设，该序列不是白噪声序列，不具有纯随机性


#实验三
x <- read.csv('data/file3.csv')
plot(x$sunsplot,type="o",col="green",lwd=2)
#时序图有上升趋势，明显不是平稳的
for (i in 1:24) print(Acf(x$sunsplot,i))
corr3 <- acf(x$sunsplot,lag.max = 24)
corr3$acf
Box.test(x$sunsplot,lag = 6,type = "Box-Pierce")
#拒绝原假设，不具有纯随机性，不是白噪声序列

#在大样本条件下，计算LB统计量来判断纯随机性
n <- length(x$sunsplot)
m=6
LB=0
for (i in 1:m) {
  s=n*(n+2)*(((corr3$acf^2)[i])/(n-i))
  LB=LB+s
}
LB
P <- 1-pchisq(LB,m,ncp=0,lower.tail = T,log.p = F)
P
#P值为0，拒绝原假设，因此该序列不具有纯随机性
y <- c()
for (i in 1:n) {
  y[i] <- x$sunsplot[i]-x$sunsplot[i-1]
}
y
y <- na.omit(y)#去NA
n1 <- length(y)
plot(y,type = "o",col="blue",lwd=1.8,main = "y-时序图",xlab="year")
for (i in 1:24) {
  print(Acf(y,i))
}
corr4 <- acf(y,lag.max = 24)
corr4$acf
#根据自相关图，时间序列y是非平稳的
#要是时间序列平稳，可进行二次差分
LB=0
for (i in 1:m) {
  s=n1*(n1+2)*(((corr4$acf^2)[i])/(n1-i))
  LB=LB+s
}
LB
P <- 1-pchisq(LB,m,ncp=0,lower.tail = T,log.p = F)
P
Box.test(y,lag = 6,type = 'Box-Pierce')#拒绝原假设
#P值小于0.05，拒绝原假设，不具有纯随机性
z <- c()
for (i in 1:n) {
  z[i] <- y[i]-y[i-1]
}
z
z <- na.omit(z)#去NA
n2 <- length(z)
plot(z,type = "o",col="blue",lwd=1.8,main = "y-时序图",xlab="year")
corr5 <- acf(z,lag.max = 24)
#95%的自相关系数都控制在2倍标准差之内，故序列具有平稳性
corr5$acf
Box.test(z,lag = 6,type = "Box-Pierce")
#P值为0.116，大于显著性水平0.05，没有充分的理由拒绝原假设，
#因此，二次查分后的序列是白噪声序列，具有纯随机性和平稳性
```









